(()=>{
'use strict';
const M=SAIPair,frames={sumin:document.getElementById('sumin-frame'),jiwoo:document.getElementById('jiwoo-frame')};
let state=M.initial(),active='sumin',lang='ko';
try{const saved=JSON.parse(localStorage.getItem('sai-pair-v1')||'null');if(saved?.version===1&&saved.people?.sumin&&saved.people?.jiwoo&&Array.isArray(saved.events)&&Array.isArray(saved.notices)&&Array.isArray(saved.messages)&&saved.slots?.sumin&&saved.garden){state=saved;if(state.breath&&['waiting','running'].includes(state.breath.status))state.breath.status='cancelled';if(state.dateSession?.status==='active')state.dateSession.status='cancelled'}}catch{}
const t=(ko,ja)=>lang==='ja'?ja:ko;
const post=(id,msg)=>frames[id].contentWindow?.postMessage({channel:'sai-pair',...msg},'*');
function save(){try{localStorage.setItem('sai-pair-v1',JSON.stringify(state))}catch{}}
function broadcast(actor,reset=false){for(const who of M.USERS)post(who,{type:'state',who,state,actor,reset});updateHost()}
function updateHost(){M.USERS.forEach(id=>{const count=state.notices.filter(n=>n.to===id&&!n.read).length;document.querySelectorAll(`[data-count="${id}"]`).forEach(e=>{e.textContent=count?String(Math.min(count,99)):'';e.hidden=!count})});const eventCount=state.events.length;document.getElementById('shared-count').textContent=`${eventCount}${t('개의 함께한 기록','件の共同記録')}`;}
function act(who,action){const next=M.reduce(state,who,action);if(next===state)return;state=next;save();broadcast(who);const actor=who==='sumin'?t('수민','スミン'):t('지우','ジウ');document.getElementById('connection-status').textContent=actor+t('의 선택이 상대 화면에 반영됐어요','の選択を相手の画面に反映しました');}
window.addEventListener('message',e=>{const who=M.USERS.find(id=>frames[id].contentWindow===e.source);if(!who||e.data?.channel!=='sai-pair')return;if(e.data.type==='ready')post(who,{type:'state',who,state});if(e.data.type==='action')act(who,e.data.action)});
const doc=JSON.parse(document.getElementById('phone-document').textContent);for(const who of M.USERS){frames[who].name=who;frames[who].srcdoc=doc}
setInterval(()=>{const now=Date.now();if(state.breath?.status==='running'&&now-state.breath.started>=24000){state=M.reduce(state,'sumin',{type:'breath-finish'},now);save();broadcast();return}if(state.breath?.status==='running'||state.dateSession?.status==='active')M.USERS.forEach(id=>post(id,{type:'tick',now}))},250);
function switchPhone(id){post(id,{type:'refresh'});active=id;document.body.dataset.active=id;document.querySelectorAll('[data-phone]').forEach(b=>{const on=b.dataset.phone===id;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',String(on))})}
document.querySelectorAll('[data-phone]').forEach(b=>b.onclick=()=>switchPhone(b.dataset.phone));
const scenarios={calendar:{tab:'calendar',feature:'mode',day:'2026-09-12',ko:'① 각 화면에서 데이트 모드를 골라보세요. ② 같은 모드를 고르면 양쪽 달력에 약속이 생겨요.',ja:'① それぞれの画面でデートを選んで。② 同じモードで両方のカレンダーに約束が残ります。'},care:{tab:'calendar',feature:'care',day:'2026-09-14',ko:'① 날짜 상세에서 필요한 배려를 선택해요. ② 상대 화면에서 “내가 챙길게”를 눌러보세요.',ja:'① 日付の詳細でほしい気づかいを選ぶ。② 相手画面で「私がするね」を押してください。'},pulse:{tab:'connect',feature:'pulse',ko:'① 한쪽에서 동의하고 심박을 보내요. ② 상대 화면 아래에 도착한 리듬을 확인하고 “느꼈어”를 눌러요.',ja:'① 一方で同意して心拍を送る。② 相手画面の下に届いたリズムを確認し、受け取ってください。'},breathe:{tab:'connect',feature:'breathe',ko:'① 한쪽에서 초대해요. ② 상대가 참여하면 같은 24초 호흡 가이드가 시작돼요.',ja:'① 一方から招待。② 相手が参加すると同じ24秒の呼吸ガイドが始まります。'},walk:{tab:'connect',feature:'walk',ko:'① 초대하고 상대가 참여해요. ② 각자 예시 걸음을 채우면 함께 산책 목표를 달성해요.',ja:'① 招待し、相手が参加。② それぞれサンプル歩数を増やすと共同目標を達成します。'},date:{tab:'connect',feature:'date',ko:'① 초대와 참여 후 각자 순간을 표시해요. ② 함께 마치면 두 사람의 달력에 같은 추억이 남아요.',ja:'① 招待・参加後、それぞれ瞬間をマーク。② 終了すると両方のカレンダーに思い出が残ります。'},garden:{tab:'connect',feature:'garden',ko:'① 각자 수면 사용에 동의해요. ② 양쪽에서 푹 잔 날 예시를 적용하면 꽃이 피어요.',ja:'① それぞれ睡眠使用に同意。② 両方でよく眠れた日の例を適用すると花が咲きます。'},rhythm:{tab:'connect',feature:'rhythm',ko:'① 각자 편한 시간을 골라요. ② 겹치는 시간 중 같은 시간을 선택하면 통화 약속이 생겨요.',ja:'① それぞれ都合のいい時間を選ぶ。② 重なる同じ時間を選ぶと通話の約束になります。'}};
let selectedScenario='calendar';
function scenario(k){selectedScenario=k;const s=scenarios[k];document.getElementById('scenario-guide').textContent=s[lang];M.USERS.forEach(id=>post(id,{type:'navigate',...s}));document.querySelectorAll('[data-scenario]').forEach(b=>b.classList.toggle('selected',b.dataset.scenario===k))}
document.querySelectorAll('[data-scenario]').forEach(b=>b.onclick=()=>scenario(b.dataset.scenario));
document.getElementById('reset-top').onclick=()=>document.getElementById('reset-dialog').showModal();
document.getElementById('reset-demo').onclick=()=>document.getElementById('reset-dialog').showModal();document.getElementById('reset-cancel').onclick=()=>document.getElementById('reset-dialog').close();document.getElementById('reset-confirm').onclick=()=>{state=M.initial();save();broadcast(null,true);document.getElementById('reset-dialog').close();document.getElementById('connection-status').textContent=t('두 화면을 초기 상태로 되돌렸어요','2画面を初期状態に戻しました');document.getElementById('scenario-guide').textContent=t('아래 화면에서 자유롭게 체험하거나, 위에서 시연할 기능을 골라보세요.','画面で自由に体験するか、上から機能を選んでください。');document.querySelectorAll('[data-scenario]').forEach(b=>b.classList.remove('selected'))};
document.getElementById('host-language').onclick=()=>{lang=lang==='ko'?'ja':'ko';document.documentElement.lang=lang;document.querySelectorAll('[data-ko]').forEach(e=>e.textContent=e.dataset[lang]);document.getElementById('host-language').textContent=lang==='ko'?'KR / JP':'JP / KR';M.USERS.forEach(id=>post(id,{type:'language',lang}));document.getElementById('scenario-guide').textContent=scenarios[selectedScenario][lang];updateHost()};
updateHost();switchPhone(active);
})();
