(()=>{'use strict';
const version=document.body.dataset.version, q=new URLSearchParams(location.search);
let lang=q.get('lang')==='ja'?'ja':q.get('lang')==='ko'?'ko':navigator.language.startsWith('ja')?'ja':'ko';
const t=(ko,ja)=>lang==='ja'?ja:ko;
const app=document.querySelector('#app'),dialog=document.querySelector('#experience');
let timer=null,opener=null,activeFeature='sleep';
const track=(name,extra={})=>window.gtag?.('event',name,{teaser_variant:`teaser${version}`,site_language:lang,...extra});
const icons={sleep:'☾',pulse:'♡',breathe:'◎',care:'☁',moment:'✧',garden:'✿'};
const features=()=>[
 ['sleep',t('잘 잤어? 그 다음의 다정함.','「よく眠れた？」の、その先。'),t('내가 허락한 밤만, 너에게.','シェアしたい夜だけ、あなたに。'),t('수면 공유','睡眠シェア'),'lavender'],
 ['pulse',t('말 대신, 두근.','言葉のかわりに、ドキドキ。'),t('지금 이 리듬을 너에게 보내기.','今のリズムを、あなたへ。'),t('심박 보내기','心拍を送る'),'peach'],
 ['breathe',t('잠깐, 같이 숨 쉴래?','少しだけ、一緒に深呼吸。'),t('바쁜 하루에 둘만의 작은 쉼표.','忙しい一日に、ふたりのひと息。'),t('함께 호흡','一緒に呼吸'),'sage'],
 ['care',t('오늘은, 조금 천천히.','今日は、少しゆっくり。'),t('필요한 배려를 먼저 알려줘요.','ほしい気づかいを、そっと伝える。'),t('배려 체크인','気づかいチェックイン'),'cream'],
 ['moment',t('사진 밖의 설렘까지.','写真に写らない、ときめきまで。'),t('내가 고른 순간과 리듬을 함께 기록.','選んだ瞬間とリズムを、ひとつに。'),t('순간 기록','思い出を残す'),'rose'],
 ['garden',t('잘 잔 밤이, 꽃이 된다면.','よく眠れた夜が、花になったら。'),t('둘의 작은 습관으로 자라는 정원.','ふたりの小さな習慣で育つ庭。'),t('수면 정원','おやすみガーデン'),'sage']
];
const button=(label,action,cls='primary')=>`<button class="${cls}" data-action="${action}">${label}</button>`;
const demoButton=id=>button(t('한번 해보기','体験してみる')+' ↗',id,'try');
function nav(){return `<header class="nav"><a class="brand" href="/?lang=${lang}" aria-label="SAI 홈">sai<span>○</span></a><a class="nav-explore" href="#explore">${t('우리 사이 체험하기','ふたりのSAIを体験')}</a><div class="nav-right"><button class="language" data-action="language" aria-label="한국어 / 日本語">${lang==='ko'?'KO <span>/ JA</span>':'JA <span>/ KO</span>'}</button>${button(t('먼저 만나기','いち早く出会う'),'signup','primary small')}</div></header>`;}
function price(){return `<section class="price-section" id="pair"><p class="eyebrow">ONE FOR ME. ONE FOR YOU.</p><h2>${t('링은 두 개.<br>사이는 하나.','リングはふたつ。<br>ふたりのSAIは、ひとつ。')}</h2><p>${t('예쁜 커플 링을 넘어,<br>서로의 하루를 알아가는 새로운 습관.','おそろいの、その先へ。<br>お互いの毎日を知る、新しい習慣。')}</p><div class="price-line"><span>${t('커플 링 2개 세트','ペアリング・2個セット')}</span><strong>${t('₩300,000','₩300,000 KRW')}</strong><span>${t('출시 예정가','韓国での発売予定価格')}</span></div><p class="fine">${t('출시 전 기획 가격입니다. 최종 사양·가격 및 멤버십 조건은 추후 안내합니다.','発売前の予定価格です。日本での販売価格・最終仕様・メンバーシップ条件は後日ご案内します。')}</p>${button(t('우리의 시작을 기다릴게요','ふたりのはじまりを待つ'),'signup')}<p class="fine">${t('출시 소식 받기 · 지금 결제하지 않아요','リリース通知を受け取る・お支払いはありません')}</p></section>`;}
function footer(){return `<footer><a class="brand" href="/?lang=${lang}">sai<span>○</span></a><p>${t('서로를 더 잘 아는, 우리만의 사이.','お互いをもっと知る、ふたりだけのSAI。')}</p><p class="fine">${t('체험은 예시 데이터로 작동합니다. 실제 센서 측정이나 상대방 전송은 이루어지지 않습니다.','体験はサンプルデータを使用します。実際のセンサー計測や相手への送信は行いません。')}</p><a class="review-link" href="/teaser-review.html?lang=${lang}">${t('티저 비교하기','ティザーを比較')}</a></footer>`;}
function playground(){const f=features();return `<main><section class="play-hero"><div class="hero-copy"><p class="eyebrow">A LITTLE CLOSER, EVERY DAY.</p><h1>${t('우리 사이에,<br><em>작은 신호 하나.</em>','ふたりの間に、<br><em>小さなサイン。</em>')}</h1><p class="lead">${t('잘 잤는지, 보고 싶은지, 쉬고 싶은지.<br>링 하나씩 끼고, 서로를 조금 더 알아가요.','よく眠れた？ 会いたい？ 少し休みたい？<br>リングをひとつずつ。もっと、あなたを知る。')}</p><a class="primary" href="#explore">${t('우리 사이 미리 체험하기','ふたりのSAIを体験する')} ↘</a><p class="hero-price">${t('둘을 위한 링 2개 · 30만 원 예정','ふたりのリング2個・韓国発売予定価格 ₩300,000')}</p></div><div class="play-art"><div class="orbit"></div><img class="hero-rings" src="/assets/hero-ring-v3-transparent.webp" alt="${t('실버와 골드 SAI 커플 링','シルバーとゴールドのSAIペアリング')}" fetchpriority="high"><div class="floating bubble-one"><i>☾</i> ${t('푹 잤어?','よく眠れた？')} <span>♡</span></div><div class="floating bubble-two"><span class="mini-pulse">⌁</span> ${t('내 리듬, 도착!','リズム、届いた！')}</div><span class="art-caption">YOU + ME = SAI</span></div></section><section class="playground section" id="explore"><div class="section-intro"><p class="eyebrow">SMALL MOMENTS. BIG FEELINGS.</p><h2>${t('궁금한 마음부터,<br>하나씩 눌러봐.','気になる気持ちから、<br>ひとつずつ、タップ。')}</h2><p>${t('연결 없이도, 지금 여기서.<br>각 기능을 짧은 예시로 체험해보세요.','接続なしで、今ここで。<br>それぞれの機能を、短い体験で。')}</p></div><div class="feature-grid">${f.map(([id,title,desc,label,color])=>`<article class="feature-card ${color}"><div class="card-head"><span>${label}</span><span class="card-dot"></span></div><div class="feature-visual ${id}">${visual(id)}</div><h3>${title}</h3><p>${desc}</p>${demoButton(id)}</article>`).join('')}</div></section><section class="trust section"><div><span class="eyebrow">ONLY US. ALWAYS YOUR CHOICE.</span><h2>${t('가까워지는 만큼,<br>내 선택도 소중하게.','近づくほど、<br>自分の選択も大切に。')}</h2><p>${t('공유할 데이터는 직접 고르고, 언제든 멈춰요.<br>마음을 단정하는 숫자보다, 서로에게 묻는 다정함.','シェアするデータは自分で選び、いつでも止められる。<br>数字で決めつけず、相手にたずねるやさしさを。')}</p></div><div class="privacy-card"><span>♡</span><strong>${t('나와, 내가 선택한 한 사람.','わたしと、わたしが選んだひとり。')}</strong><p>${t('우리 사이의 작은 약속','ふたりだけの小さな約束')}</p><div>${t('공유는 내가 정해요','シェアは自分で選ぶ')} <b>✓</b></div></div></section>${price()}</main>`;}
function visual(id){return ({sleep:`<div class="sleep-note"><span>☾</span><small>${t('어젯밤의 나','昨夜のわたし')}</small><strong>7h 42m</strong><div class="bars">${[20,34,25,44,31,48,33,28,40,23,32,20].map(x=>`<i style="height:${x}px"></i>`).join('')}</div></div>`,pulse:'<div class="big-heart">♡</div><span class="pulse-stroke">⌁⌁⌁</span>',breathe:'<div class="breath-mini"><span>YOU<br>＋<br>ME</span></div>',care:`<div class="message-chip">${t('오늘은 조용히 쉬고 싶어 ☁','今日は、静かに休みたい ☁')}</div><div class="message-chip reply">${t('응, 천천히 답해도 돼 ♡','うん、返信はゆっくりでいいよ ♡')}</div>`,moment:`<div class="moment-photo"><img src="/assets/couple-night-v6.webp" alt="" loading="lazy"><span>${t('너와 걷던 그 밤 ✧','ふたりで歩いたあの夜 ✧')}</span></div>`,garden:'<div class="garden-art"><span>✿</span><span>❀</span><span>✿</span><i>︶</i></div>'})[id];}
function editorial(){return `<main><section class="editorial-hero"><p class="eyebrow">SAI · SMART RINGS FOR TWO</p><h1>${t('둘만 아는<br><em>연결.</em>','ふたりだけの、<br><em>つながり。</em>')}</h1><p class="lead">${t('가장 가까운 사람을,<br>조금 더 가까이.','いちばん近い人を、<br>もう少し近くに。')}</p><div class="editorial-product"><img src="/assets/product-rings.webp" alt="${t('실버와 샴페인 골드 SAI 링 두 개','シルバーとシャンパンゴールドのSAIリング2個')}" fetchpriority="high"></div><div class="hero-bottom"><p>${t('커플 링 2개 세트 · 30만 원 예정','ペアリング2個・韓国発売予定価格 ₩300,000')}</p><a href="#explore">${t('연결을 경험하다','つながりを体験する')} ↓</a></div></section><section class="cinema"><img src="/assets/ring-hands-closeup-v6.webp" alt="${t('반지를 끼고 포개진 두 사람의 손','リングをつけて重ねたふたりの手')}" loading="lazy"><div><p class="eyebrow">BEYOND MATCHING RINGS.</p><h2>${t('같은 링에서,<br>함께하는 일상으로.','おそろいのリングから、<br>寄り添う毎日へ。')}</h2></div></section><section class="editorial-story section"><p class="eyebrow">GOOD MORNING, A LITTLE CLOSER.</p><h2>${t('“잘 잤어?”가<br>조금 더 깊어지다.','「よく眠れた？」が、<br>もう少し深くなる。')}</h2><p class="lead">${t('공유하기로 한 밤의 기록.<br>오늘의 너를 배려하는 작은 시작.','シェアを選んだ、昨夜の記録。<br>今日のあなたを気づかう、小さなはじまり。')}</p><div class="story-pair"><img src="/assets/couple-morning-v6.webp" alt="${t('둘이 함께 보내는 아침','ふたりで過ごす朝')}" loading="lazy"><div class="story-note"><span>☾</span><h3>${t('어젯밤, 7시간 42분.','昨夜は、7時間42分。')}</h3><p>${t('숫자는 오늘의 대화를 시작하는 힌트.<br>공유 여부는 내가 정해요.','数字は、今日の会話をはじめるヒント。<br>シェアするかは、自分で決める。')}</p>${demoButton('sleep')}<small>${t('예시 데이터','サンプルデータ')}</small></div></div></section><section class="dark-section" id="explore"><div class="section"><p class="eyebrow">FEEL IT, BEFORE YOU WEAR IT.</p><h2>${t('설명보다,<br>한 번의 경험.','説明よりも、<br>ひとつの体験。')}</h2><div class="tab-list" role="tablist" aria-label="${t('기능 선택','機能を選ぶ')}">${['pulse','breathe','moment'].map((id,i)=>`<button role="tab" id="tab-${id}" aria-controls="tab-panel" aria-selected="${i===0}" tabindex="${i===0?'0':'-1'}" data-tab="${id}">${features().find(f=>f[0]===id)[3]}</button>`).join('')}</div><div id="tab-panel" role="tabpanel" aria-labelledby="tab-pulse"></div></div></section><section class="quiet-statement section"><p class="eyebrow">INTIMACY, ON YOUR TERMS.</p><h2>${t('모든 걸 공유할 필요는 없어.<br><em>소중한 것만, 너에게.</em>','すべてをシェアしなくていい。<br><em>大切なことだけ、あなたに。</em>')}</h2><p>${t('수면도, 심박도, 나의 페이스대로.<br>공유할 정보와 순간을 직접 선택하세요.','睡眠も、心拍も、自分のペースで。<br>シェアする情報と瞬間を、自分で選ぶ。')}</p>${demoButton('care')}</section>${price()}</main>`;}
function panel(id){const f=features().find(f=>f[0]===id);document.querySelector('#tab-panel').innerHTML=`<div class="panel-art ${id}">${visual(id)}</div><div class="panel-copy"><h3>${f[1]}</h3><p>${f[2]}</p>${demoButton(id)}<small>${t('예시 데이터로 가볍게 체험','サンプルデータで気軽に体験')}</small></div>`;document.querySelectorAll('[data-tab]').forEach(b=>{b.setAttribute('aria-selected',b.dataset.tab===id);b.tabIndex=b.dataset.tab===id?0:-1;});document.querySelector('#tab-panel').setAttribute('aria-labelledby','tab-'+id);}
function render(){document.documentElement.lang=lang;document.title=t('SAI — '+(version==='2'?'작은 연결의 놀이터':'둘만 아는 연결'),'SAI — '+(version==='2'?'ふたりの小さな遊び場':'ふたりだけのつながり'));app.innerHTML=nav()+(version==='2'?playground():editorial())+footer();if(version==='3')panel('pulse');}
function close(){clearInterval(timer);timer=null;dialog.close();opener?.focus();}
function open(id){activeFeature=id;opener=document.activeElement;clearInterval(timer);const f=features().find(f=>f[0]===id);dialog.innerHTML=`<button class="close" data-action="close" aria-label="${t('닫기','閉じる')}">×</button><span class="eyebrow">${id==='signup'?'HELLO, SAI.':t('미리 만나는 SAI · 예시 체험','SAIのプレビュー・サンプル体験')}</span><h2 id="dialog-title">${id==='signup'?t('우리 사이, 먼저 만나기.','ふたりのSAIに、いち早く。'):f[1]}</h2><div id="demo-body"></div>${id==='signup'?'':`<p class="demo-disclaimer">${t('예시 데이터입니다. 실제 측정·전송은 하지 않아요.','サンプルデータです。実際の計測・送信は行いません。')}</p>`}`;dialog.showModal();track('teaser_demo_open',{feature:id});({sleep:sleepDemo,pulse:pulseDemo,breathe:breathDemo,care:careDemo,moment:momentDemo,garden:gardenDemo,signup:signup})[id]();}
const body=html=>document.querySelector('#demo-body').innerHTML=html;
function sleepDemo(){body(`<div class="demo-sleep"><span>☾</span><strong>7h 42m</strong><p>${t('나의 어젯밤 수면 · 예시','昨夜のわたしの睡眠・サンプル')}</p></div><label class="switch-row">${t('이 수면 기록을 상대에게 공유','この睡眠記録を相手にシェア')}<input id="sleep-share" type="checkbox" role="switch"></label><div class="recipient" id="sleep-recipient" aria-live="polite">${t('아직 나만 볼 수 있어요.','まだ、自分だけに見えます。')}</div>`);document.querySelector('#sleep-share').onchange=e=>{document.querySelector('#sleep-recipient').innerHTML=e.target.checked?t('상대 화면 · “푹 잤구나. 오늘도 좋은 하루 보내 ♡”','相手の画面・「よく眠れたんだね。今日もいい一日を ♡」'):t('공유를 멈췄어요. 이제 나만 볼 수 있어요.','シェアを停止。自分だけに見えます。');track('teaser_demo_complete',{feature:'sleep'});};}
function pulseDemo(){body(`<div class="demo-heart">♡</div><p>${t('예시 심박 리듬 78 BPM.<br>숫자가 감정을 단정하지는 않아요.','サンプルの心拍リズム、78 BPM。<br>数字だけで気持ちは決められません。')}</p><label class="consent"><input type="checkbox" id="pulse-consent">${t('이 리듬을 공유할게요','このリズムをシェアする')}</label><button class="primary wide" id="pulse-send" disabled>${t('두근, 보내기','ドキドキを送る')}</button><div class="recipient" id="pulse-status" aria-live="polite">${t('상대에게 보낼 준비 중','相手に届ける準備中')}</div>`);const c=document.querySelector('#pulse-consent'),b=document.querySelector('#pulse-send');c.onchange=()=>b.disabled=!c.checked;b.onclick=()=>{b.disabled=true;document.querySelector('.demo-heart').classList.add('beating');document.querySelector('#pulse-status').innerHTML=`${t('상대에게 리듬이 도착했어요.','相手にリズムが届きました。')} <button class="try" id="pulse-reply">${t('느꼈어 ♡','受け取ったよ ♡')}</button>`;document.querySelector('#pulse-reply').onclick=()=>{document.querySelector('#pulse-status').textContent=t('너의 답장도 도착했어. 오늘도 가까이 ♡','あなたの返事も届いた。今日もそばに ♡');track('teaser_demo_complete',{feature:'pulse'});};};}
function breathDemo(){body(`<p>${t('24초 동안, 같은 호흡 가이드를 따라가요.<br>실제 심박 동기화 결과를 측정하는 체험은 아니에요.','24秒間、同じ呼吸ガイドに合わせて。<br>実際の心拍の同期を測定する体験ではありません。')}</p><div class="breath-orb" id="breath-orb"><span id="breath-phase">${t('함께 준비','一緒に準備')}</span></div><p id="breath-time" aria-live="polite">24s</p><button class="primary wide" id="breath-start">${t('둘이 함께 시작하기','ふたりでスタート')}</button>`);document.querySelector('#breath-start').onclick=e=>{e.target.disabled=true;const start=Date.now();document.querySelector('#breath-orb').classList.add('running');const tick=()=>{const elapsed=Math.floor((Date.now()-start)/1000),left=Math.max(0,24-elapsed);document.querySelector('#breath-time').textContent=left+'s';document.querySelector('#breath-phase').textContent=Math.floor(elapsed/4)%2?t('천천히 내쉬어요','ゆっくり吐いて'):t('천천히 들이쉬어요','ゆっくり吸って');if(!left){clearInterval(timer);document.querySelector('#breath-orb').classList.remove('running');document.querySelector('#breath-phase').textContent=t('같이 쉬었어요 ♡','一緒にひと息 ♡');document.querySelector('#breath-start').textContent=t('다시 해보기','もう一度');document.querySelector('#breath-start').disabled=false;track('teaser_demo_complete',{feature:'breathe'});}};tick();timer=setInterval(tick,250);};}
function careDemo(){body(`<p>${t('오늘 나에게 필요한 배려를 골라봐요.','今日、ほしい気づかいを選んで。')}</p><div class="care-options">${[t('조용히 쉬고 싶어 ☁','静かに休みたい ☁'),t('함께 걷고 싶어 ♡','一緒に歩きたい ♡'),t('이야기를 들어줘 ✧','話を聞いてほしい ✧')].map((s,i)=>`<button class="care-choice" data-care="${i}">${s}</button>`).join('')}</div><div class="recipient" id="care-result" aria-live="polite">${t('선택한 메시지만 상대에게 보여줘요.','選んだメッセージだけを相手に。')}</div>`);document.querySelectorAll('[data-care]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-care]').forEach(x=>x.classList.toggle('selected',x===b));document.querySelector('#care-result').innerHTML=`<small>${t('상대의 답장 · 예시','相手からの返事・サンプル')}</small><strong>${[t('응, 천천히 답해도 괜찮아.','うん、返信はゆっくりでいいよ。'),t('좋아. 오늘 저녁 같이 걸을까?','いいね。今夜、一緒に歩こうか？'),t('내가 듣고 있을게.','ちゃんと聞いているよ。')][+b.dataset.care]}</strong>`;track('teaser_demo_complete',{feature:'care'});});}
function momentDemo(){body(`<img class="demo-photo" src="/assets/couple-night-v6.webp" alt="${t('손을 잡고 걷는 둘','手をつないで歩くふたり')}"><p>${t('너와 걷던 그 밤.<br>예시 심박 86 BPM과 내가 고른 기억을 함께.','ふたりで歩いたあの夜。<br>サンプル心拍86 BPMと、自分で選んだ思い出。')}</p><button class="primary wide" id="save-moment">${t('이 순간에 별 남기기 ✧','この瞬間に星をつける ✧')}</button><div class="recipient" id="moment-status" aria-live="polite"></div>`);document.querySelector('#save-moment').onclick=e=>{e.target.disabled=true;document.querySelector('#moment-status').textContent=t('✧ 둘의 예시 아카이브에 담았어요. 창을 닫으면 초기화됩니다.','✧ ふたりのサンプルアーカイブへ。閉じるとリセットされます。');track('teaser_demo_complete',{feature:'moment'});};}
function gardenDemo(){body(`<div class="demo-garden" id="garden-flower">♧</div><p>${t('각자 잘 잔 밤을 선택해보세요.','それぞれ、よく眠れた夜を選んで。')}</p><label class="switch-row">${t('나도 푹 잤어요','わたしも、ぐっすり')}<input type="checkbox" id="garden-me"></label><label class="switch-row">${t('너도 푹 잤어요','あなたも、ぐっすり')}<input type="checkbox" id="garden-you"></label><div class="recipient" id="garden-result" aria-live="polite">${t('둘의 아침을 기다리는 중','ふたりの朝を待っています')}</div>`);dialog.querySelectorAll('input').forEach(i=>i.onchange=()=>{const done=document.querySelector('#garden-me').checked&&document.querySelector('#garden-you').checked;document.querySelector('#garden-flower').textContent=done?'✿':'♧';document.querySelector('#garden-flower').classList.toggle('bloom',done);document.querySelector('#garden-result').textContent=done?t('둘의 정원에 첫 꽃이 피었어요!','ふたりの庭に、最初の花が咲きました！'):t('둘의 좋은 밤이 모이면 꽃이 피어요.','ふたりのいい夜が集まると、花が咲きます。');if(done)track('teaser_demo_complete',{feature:'garden'});});}
function signup(){body(`<p>${t('SAI의 출시 소식과 혜택을 가장 먼저 받아보세요.','SAIのリリース情報と特典を、いち早く。')}</p><form id="signup-form"><label class="field">${t('이메일','メールアドレス')}<input type="email" name="email" autocomplete="email" required maxlength="254" placeholder="you@example.com" data-clarity-mask="true"></label><label class="field">${t('거주 국가','お住まいの国')}<select name="country"><option value="KR" ${lang==='ko'?'selected':''}>${t('한국','韓国')}</option><option value="JP" ${lang==='ja'?'selected':''}>${t('일본','日本')}</option><option value="OTHER">${t('그 외','その他')}</option></select></label><label class="consent"><input type="checkbox" name="consent" required><span>${t('사이의 출시 소식 및 혜택 안내를 이메일로 받아볼게요.','SAIのリリース情報および特典のご案内をメールで受け取ります。')}</span></label><button class="primary wide" type="submit">${t('출시 소식 받기','リリース通知を受け取る')}</button><p id="form-status" role="status"></p></form>`);document.querySelector('#signup-form').onsubmit=async e=>{e.preventDefault();const form=e.target,b=form.querySelector('button');b.disabled=true;const fields=new FormData(form),utm={};['utm_source','utm_medium','utm_campaign','utm_content','utm_term'].forEach(k=>{if(q.get(k))utm[k]=q.get(k);});try{const res=await fetch('/api/waitlist',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:fields.get('email'),country:fields.get('country'),language:lang,market:lang==='ja'?'JP':'KR',consent:true,consent_version:'2026-09-17',budget:'undecided',client_language:navigator.language,client_timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,...utm})});if(!res.ok)throw Error();body(`<div class="signup-success">♡<h3>${t('우리의 시작, 가장 먼저 전할게요.','ふたりのはじまりを、いち早く。')}</h3><p>${t('사전 신청이 완료됐어요.','事前登録が完了しました。')}</p></div>`);track('teaser_waitlist_success');}catch{document.querySelector('#form-status').textContent=t('등록하지 못했어요. 잠시 후 다시 시도해주세요.','登録できませんでした。少し時間をおいてお試しください。');b.disabled=false;}};}
app.addEventListener('click',e=>{const b=e.target.closest('[data-action],[data-tab]');if(!b)return;if(b.dataset.tab){panel(b.dataset.tab);return;}const action=b.dataset.action;if(action==='language'){lang=lang==='ko'?'ja':'ko';q.set('lang',lang);history.replaceState(null,'',location.pathname+'?'+q+location.hash);render();return;}open(action);});
app.addEventListener('keydown',e=>{const tabs=[...document.querySelectorAll('[role="tab"]')];if(!tabs.includes(e.target)||!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();let i=tabs.indexOf(e.target);i=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;panel(tabs[i].dataset.tab);tabs[i].focus();});
dialog.addEventListener('click',e=>{if(e.target.closest('[data-action="close"]'))close();if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close();}});dialog.addEventListener('cancel',e=>{e.preventDefault();close();});dialog.addEventListener('close',()=>clearInterval(timer));render();
})();
