const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
function fixture(blocked=false){const nodes=new Map(),memory={};function el(s){if(!nodes.has(s))nodes.set(s,{innerHTML:'',textContent:'',value:'',open:false,classList:{add(){},remove(){},toggle(){}},setAttribute(){},addEventListener(){},showModal(){this.open=true},close(){this.open=false},querySelector:el,focus(){},scrollIntoView(){}});return nodes.get(s)}
const tabs=['me','us','days'].map(k=>({...el('story-'+k),dataset:{visual:k}}));const storage={getItem:k=>{if(blocked)throw Error('blocked');return memory[k]},setItem:(k,v)=>{if(blocked)throw Error('blocked');memory[k]=v}};
const ctx=vm.createContext({document:{body:{dataset:{entry:'teaser'}},documentElement:{},querySelector:el,querySelectorAll:s=>s==='[data-visual]'?tabs:[],getElementById:el},localStorage:storage,sessionStorage:storage,location:{hash:''},window:{addEventListener(){},scrollTo(){}},setTimeout:()=>0,clearTimeout(){},setInterval:()=>0,clearInterval(){},FormData:class{constructor(f){this.f=f}get(k){return this.f[k]}}});
const page=fs.readFileSync(path.join(root,'teaser-v5.html'),'utf8');const script=page.match(/<script>([\s\S]*?)<\/script>/)[1];vm.runInContext(script,ctx);const run=s=>vm.runInContext(s,ctx);
assert(el('#root').innerHTML.includes('class="s5"'));assert.equal(run('teaserFeatures().length'),8);
for(const lang of ['ko','ja']){run(`lang='${lang}';render()`);const html=el('#root').innerHTML;assert(!html.includes('undefined'));assert(!html.includes('href="#today"'));assert(html.includes('href="pair-v2.html"'));assert(html.includes('YOUR DATA. OUR LITTLE WORLD.'));tabs.forEach(b=>{b.onclick();assert(el('#s5-preview').innerHTML.includes('s5-phone'));assert(el('#s5-preview').innerHTML.includes('s5-phone-bottom'))});}
for(const key of ['calendar','care','pulse','breathe','walk','garden','date','rhythm']){run(`signup('${key}')`);assert.equal(el('#signup-form select[name="feature"]').value,key)}
el('#signup-form').onsubmit({preventDefault(){},target:{email:'not-saved@example.com',country:'JP',feature:'care',budget:'mid'}});
assert.equal(run('state.interest.feature'),'care');assert.equal(run('state.interest.country'),'JP');assert.equal(run('state.interest.email'),undefined);assert(!JSON.stringify(memory).includes('not-saved@example.com'));assert(el('#modal').innerHTML.includes('href="pair-v2.html"'));run("location.hash='#teaser';render()");assert(el('#root').innerHTML.includes('class="s5"'));
console.log('PASS teaser:',blocked?'storage blocked':'storage available','— standalone entry, KR/JP content, three visual previews, eight interest presets, current app links, local response without email persistence.');}
fixture();fixture(true);
