const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
function fixture(blocked=false){const nodes=new Map(),memory={};function el(s){if(!nodes.has(s))nodes.set(s,{innerHTML:'',textContent:'',value:'',open:false,classList:{add(){},remove(){},toggle(){}},setAttribute(){},addEventListener(){},showModal(){this.open=true},close(){this.open=false},querySelector:el,focus(){},scrollIntoView(){}});return nodes.get(s)}
const tabs=['date','care','pulse'].map(k=>({...el('story-'+k),dataset:{story:k}}));const storage={getItem:k=>{if(blocked)throw Error('blocked');return memory[k]},setItem:(k,v)=>{if(blocked)throw Error('blocked');memory[k]=v}};
const ctx=vm.createContext({document:{body:{dataset:{entry:'teaser'}},documentElement:{},querySelector:el,querySelectorAll:s=>s==='[data-story]'?tabs:[],getElementById:el},localStorage:storage,sessionStorage:storage,location:{hash:''},window:{addEventListener(){},scrollTo(){}},setTimeout:()=>0,clearTimeout(){},setInterval:()=>0,clearInterval(){},FormData:class{constructor(f){this.f=f}get(k){return this.f[k]}}});
const page=fs.readFileSync(path.join(root,'teaser.html'),'utf8');const script=page.match(/<script>([\s\S]*?)<\/script>/)[1];vm.runInContext(script,ctx);const run=s=>vm.runInContext(s,ctx);
assert(el('#root').innerHTML.includes('teaser-v2'));assert.equal(run('teaserFeatures().length'),8);
for(const lang of ['ko','ja']){run(`lang='${lang}';render()`);const html=el('#root').innerHTML;assert(!html.includes('undefined'));assert(!html.includes('href="#today"'));assert(html.includes('href="pair.html"'));assert(html.includes('OUR RHYTHM CALENDAR'));for(const key of ['calendar','care','pulse','breathe','walk','garden','date','rhythm'])assert(html.includes(`data-interest="${key}"`));tabs.forEach(b=>{b.onclick();assert(el('#teaser-story').innerHTML.includes('story-person'));assert(el('#teaser-story').innerHTML.includes('story-result'))});}
for(const key of ['calendar','care','pulse','breathe','walk','garden','date','rhythm']){run(`signup('${key}')`);assert.equal(el('#signup-form select[name="feature"]').value,key)}
el('#signup-form').onsubmit({preventDefault(){},target:{email:'not-saved@example.com',country:'JP',feature:'care',budget:'mid'}});
assert.equal(run('state.interest.feature'),'care');assert.equal(run('state.interest.country'),'JP');assert.equal(run('state.interest.email'),undefined);assert(!JSON.stringify(memory).includes('not-saved@example.com'));assert(el('#modal').innerHTML.includes('href="pair.html"'));run("location.hash='#teaser';render()");assert(el('#root').innerHTML.includes('teaser-v2'));
console.log('PASS teaser:',blocked?'storage blocked':'storage available','— standalone entry, KR/JP content, three story tabs, eight interest presets, current app links, local response without email persistence.');}
fixture();fixture(true);
for(const file of ['teaser.html','pair.html','mobile.html','mobile-single.html']){const page=fs.readFileSync(path.join(root,file),'utf8');if(file==='teaser.html'){assert(!page.includes('@import'));assert(!/<script[^>]+src=/.test(page));for(const m of page.matchAll(/href="([^"#]+\.html)(?:#[^"]*)?"/g))assert(fs.existsSync(path.join(root,m[1])),m[1]);}else assert(page.includes('teaser.html'),'latest teaser link in '+file)}
console.log('PASS artifact links: current teaser available from both paired files and the previous mobile preview; no external teaser assets.');
